services:
  postgressdb:
    image: postgres:17
    container_name: Auth_TS_Drizzel_PostgresSQL
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db_drizzel
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: